name: Website build
concurrency:
  group: ${{ github.ref }}
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Init bin repo
        env:
          BIN_TOKEN: ${{ secrets.BIN_REPO_TOKEN || github.token }}
        run: |
          git init bin-repo
          cd bin-repo
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config user.name 'Keycap Archivist Bot'
          git remote add origin https://x-access-token:${BIN_TOKEN}@github.com/thisisdefinitelyajoke/website-ascii-bin.git

      - id: nodeversion
        run: echo "NODE=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      - name: Use Node.js ${{steps.nodeversion.outputs.NODE}}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ steps.nodeversion.outputs.NODE }}
      - name: Install dependencies
        run: npx --yes pnpm install
      - name: lint
        run: npx --yes pnpm lint
      - name: Package website
        run: npx --yes pnpm package
      - name: push Website
        env:
          DISCORD_HOOK: ${{ secrets.DISCORD_HOOK }}
        run: |
          cd bin-repo
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'Keycap Archivist Bot'
          git checkout --orphan temp
          rm -rf ./*
          ls -al ../
          mv ../public/* ./
          mkdir -p ./.github/workflows
          cp -ar ../build/push.yml ./.github/workflows/push.yml
          git add .
          git commit -m "update-website" || true
          git branch -D master
          git branch -m master
          git push -f origin master || true
          cd ..
          node scripts/discord-update.js
