name: Website build
concurrency:
  group: ${{ github.ref }}
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 3 * * *'
  repository_dispatch:
    types: [database-update]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: thisisdefinitelyajoke/website-ascii-bin
          path: bin-repo
          token: ${{ secrets.BIN_REPO_TOKEN || github.token }}
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          package-manager-cache: false
      - name: Install pnpm
        run: npm install --location=global pnpm@9
      - name: Install dependencies
        run: pnpm install
      - name: Update database catalog
        run: pnpm update-db
      - name: lint
        run: pnpm lint
      - name: Package website
        run: pnpm package
      - name: push Website
        run: |
          cd bin-repo
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config user.name 'Keycap Archivist Bot'
          git checkout --orphan temp
          rm -rf ./*
          mv ../public/* ./
          mkdir -p ./.github/workflows
          cp -ar ../build/push.yml ./.github/workflows/push.yml
          git add .
          git commit -m "update-website" || true
          git branch -D main 2>/dev/null || true
          git branch -m main
          git push -f origin main || true
