name: Pull Request Package

on:
  pull_request:

jobs:
  package:
    name: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - id: nodeversion
        run: echo "NODE=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      - name: Use Node.js ${{steps.nodeversion.outputs.NODE}}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ steps.nodeversion.outputs.NODE }}
      - name: Install pnpm
        run: |
          npm install -g pnpm
          echo "$(npm config get prefix)/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: pnpm install
      - name: lint
        run: pnpm lint
      - name: Package website
        run: pnpm package
