name: Pull Request Package
on:
  pull_request:
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npx --yes pnpm install
      - name: lint
        run: npx --yes pnpm lint
      - name: Package website
        run: npx --yes pnpm package
